### ISSUE TITLE
Can't install plugin: "Error: spawn E2BIG"

### ISSUE THREAD

**Issue by GuGuss** [gnomeontherun/gitbook-plugin-swagger#1]
Hi, I'm failing at installing this plugin with Gitbook on MacOS (`"gitbook": ">=3.2"`):

```
info: install plugin "swagger" (*) from NPM with version 0.1.0
internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:387:9)
    at spawn (/Users/augustin/.gitbook/versions/3.2.2/node_modules/npm/lib/utils/spawn.js:7:13)
    at runCmd_ (/Users/augustin/.gitbook/versions/3.2.2/node_modules/npm/lib/utils/lifecycle.js:237:14)
    at runCmd (/Users/augustin/.gitbook/versions/3.2.2/node_modules/npm/lib/utils/lifecycle.js:196:5)
    at runPackageLifecycle (/Users/augustin/.gitbook/versions/3.2.2/node_modules/npm/lib/utils/lifecycle.js:160:3)
    at Array.<anonymous> (/Users/augustin/.gitbook/versions/3.2.2/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/augustin/.gitbook/versions/3.2.2/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at chain (/Users/augustin/.gitbook/versions/3.2.2/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
```

Seems related to http://stackoverflow.com/questions/37804234/grunt-error-mac-only-warning-spawn-e2big-use-force-to-continue (MacOS only) but I can't figure out how to fix it.

Any idea?

**Comment by GuGuss** [comment]
Relate to: https://github.com/GitbookIO/gitbook-cli/issues/11

**Comment by GuGuss** [comment]
I can install the plugin with: `npm i gitbook-plugin-swagger` but then, `gitbook build` fails with the following error:

```
Loading bootprint-swagger 0.13.1
Loading bootprint-json-schema 0.8.6
Loading bootprint-base 0.8.0
error: error while generating page "api/README.md":

Error: Engine 'uglify' not found. Refusing to store configuration
```

**Comment by gnomeontherun** [comment]
Are you able to install other plugins just fine? This plugin really isn't fully baked and needs more work, but curious if its isolated or not.

**Comment by alphon-sh** [comment]
Same problem here. And i'm indeed able to install other plugins.

**Comment by gnomeontherun** [comment]
I can't devote much time to this right now, but am happy to accept PRs!

**Comment by chrisdostert** [comment]
@GuGuss I made a separate issue #2 and put in a PR #3 for it (believe it's a separate issue from the original one filed here

**Comment by gnomeontherun** [comment]
Is this resolved by #3?

**Comment by alphon-sh** [comment]
Yes it is ! Only dependencies problems.

**Comment by gnomeontherun** [comment]
Great thanks!
